# 服务端口
server:
  port: 8080
# 框架配置
spring:
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/hopcraft_io_mall?serverTimezone=UTC&useSSL=false
    username: root
    password: hop/MYSQL/11
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据库连接配置
mybatis:
  mapper-locations: classpath:io/hopcraft/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
# 日志配置
logging:
  level:
    com:
      mashibing:
        mapper: debug
